ignore_patterns:
  - 'build/**'
  - '.vs/**'
  - '.vscode/**'
  - '*.o'
  - '*.obj'
  - '*.exe'
  - '*.dll'
  - '*.so'
  - '*.dylib'
  - '*.a'
  - '*.lib'
  - 'CMakeFiles/**'
  - 'cmake-build-*/**'

security_context: |
  C++ standard security considerations:
  - Memory management and buffer overflow risks
  - Pointer manipulation safety
  - Type safety and casting
  - Standard Template Library (STL) security
  - Resource management (RAII)
  - Undefined behavior risks

vulnerability_patterns:
  sqli:
    score: 8
    description: "SQL Injection in C++ database operations"
    patterns:
      - "string concatenation in SQL query"
      - "user input directly in query"
      - "lack of parameterized queries"
      - "dynamic SQL generation"
      - "raw input in database operations"
      - "query parameters from request"
      - "execute raw SQL"
      - "format string in SQL"
      - "SQL query string interpolation"
      - "sprintf SQL query"

  xss:
    score: 7
    description: "Cross-Site Scripting (XSS)"
    patterns:
      - "unescaped output to HTML"
      - "raw user data in templates"
      - "bypass content sanitization"
      - "script injection vulnerability"
      - "missing HTML encoding"
      - "template literals with user data"
      - "raw string output"
      - "cout << user_input"
      - "printf user data"
      - "string concatenation output"

  input:
    score: 9
    description: "Insufficient Input Validation"
    patterns:
      - "input validation missing"
      - "unvalidated user input"
      - "unsafe type casting"
      - "user-controlled parameter"
      - "direct use of request parameters"
      - "no input sanitization"
      - "raw form data processing"
      - "missing input boundary checks"
      - "untrusted data handling"
      - "buffer overflow risk"

  data:
    score: 8
    description: "Sensitive Data Exposure"
    patterns:
      - "sensitive data exposure"
      - "plaintext credentials"
      - "hardcoded secrets"
      - "API keys in code"
      - "unencrypted sensitive data"
      - "information disclosure"
      - "data leakage"
      - "credentials in config files"
      - "sensitive data caching"
      - "memory dump exposure"

  session:
    score: 7
    description: "Session Management Issues"
    patterns:
      - "session fixation"
      - "insecure session handling"
      - "session hijacking risk"
      - "missing session timeout"
      - "weak session ID generation"
      - "session token exposure"
      - "cookie security missing"
      - "insufficient session expiration"
      - "session data in memory"
      - "no session validation"

  config:
    score: 7
    description: "Security Misconfiguration"
    patterns:
      - "security misconfiguration"
      - "debug mode enabled"
      - "insecure permissions"
      - "missing security headers"
      - "verbose error messages"
      - "directory listing enabled"
      - "development settings in production"
      - "unsafe compiler flags"
      - "DEBUG macro enabled"
      - "unsafe preprocessor definitions"

  logging:
    score: 6
    description: "Sensitive Data Logging"
    patterns:
      - "sensitive data in logs"
      - "password logging"
      - "PII in logs"
      - "token logging"
      - "unsafe error logging"
      - "debug logging in production"
      - "authentication data in logs"
      - "cout logging sensitive"
      - "cerr exposure"
      - "fprintf sensitive data"

  crypto:
    score: 8
    description: "Insecure Cryptographic Usage"
    patterns:
      - "weak encryption"
      - "insecure random number generation"
      - "weak hash algorithm"
      - "MD5 usage"
      - "SHA1 usage"
      - "static initialization vector"
      - "hardcoded encryption key"
      - "rand() for crypto"
      - "srand() seed"
      - "mt19937 without secure seed"

  rce:
    score: 9
    description: "Remote Code Execution"
    patterns:
      - "system call with parameters"
      - "exec function with variables"
      - "popen with user input"
      - "shellexec"
      - "CreateProcess user input"
      - "WinExec variable"
      - "system("
      - "_spawn"
      - "ShellExecute"
      - "command injection"

  ssrf:
    score: 7
    description: "Server-Side Request Forgery"
    patterns:
      - "URL fetching from user input"
      - "request module with variable URL"
      - "http client with dynamic endpoint"
      - "webhook implementation"
      - "dynamic API requests"
      - "curl library user input"
      - "libcurl dynamic URL"
      - "wininet dynamic URL"
      - "boost::asio user URL"
      - "socket connection user input"

  xxe:
    score: 7
    description: "XML External Entity Injection"
    patterns:
      - "XML parser without entity restrictions"
      - "XML processing without disabling DTD"
      - "unsafe DOM parser"
      - "XML libraries with dangerous defaults"
      - "libxml without restrictions"
      - "xerces unsafe config"
      - "rapidxml entity parsing"
      - "tinyxml entity handling"
      - "pugixml entity processing"
      - "XML external entities"

  pathtra:
    score: 8
    description: "Path Traversal"
    patterns:
      - "file operations with user input"
      - "path concatenation without validation"
      - "directory traversal vulnerability"
      - "reading files with variable paths"
      - "filepath not normalized"
      - "unsafe file access"
      - "fopen user input"
      - "CreateFile user path"
      - "ifstream user input"
      - "filesystem::path user input"

  idor:
    score: 7
    description: "Insecure Direct Object Reference"
    patterns:
      - "user ID in URL parameters"
      - "missing access control checks"
      - "direct object reference in request"
      - "lack of authorization validation"
      - "resource ID manipulation vulnerability"
      - "authorization bypass risk"
      - "direct reference to database records"
      - "object level authorization missing"
      - "unsafe parameter handling"
      - "insufficient permission checking"

  secrets:
    score: 8
    description: "Hardcoded Secrets"
    patterns:
      - "hardcoded API key"
      - "password in source code"
      - "hardcoded credentials"
      - "embedded secret"
      - "private key in code"
      - "OAuth token in variables"
      - "secret key declaration"
      - "cleartext password"
      - "connection string with credentials"
      - "const char* password"

  auth:
    score: 8
    description: "Authentication Issues"
    patterns:
      - "weak password requirements"
      - "missing multi-factor authentication"
      - "insufficient credential handling"
      - "authentication bypass vulnerability"
      - "insecure password storage"
      - "broken authentication flow"
      - "credential reset weakness"
      - "session fixation vulnerability"
      - "insecure remember me function"
      - "inadequate brute force protection"

  csrf:
    score: 7
    description: "Cross-Site Request Forgery"
    patterns:
      - "missing CSRF token"
      - "state-changing operation without protection"
      - "form submission without CSRF verification"
      - "cookie-only authentication"
      - "missing SameSite attribute"
      - "actions without user confirmation"
      - "lack of request origin validation"
      - "missing anti-forgery token"
      - "insecure cross-domain requests"
      - "automatic actions without validation" 