ignore_patterns:
  - 'vendor/**'
  - 'cache/**'
  - 'logs/**'
  - 'tmp/**'
  - '.env'
  - 'composer.lock'
  - '*.cache'
  - '*.log'

security_context: |
  PHP standard security considerations:
  - Direct server-side execution environment
  - File system access risks
  - Database interaction security
  - User input handling
  - Session management
  - Error handling and logging

vulnerability_patterns:
  sqli:
    score: 9
    description: "SQL Injection in PHP database operations"
    patterns:
      - "string concatenation in SQL query"
      - "user input directly in query"
      - "lack of parameterized queries"
      - "dynamic SQL generation"
      - "raw input in database operations"
      - "query parameters from request"
      - "execute raw SQL"
      - "format string in SQL"
      - "SQL query string interpolation"
      - "unsafe database.execute"
      - "mysql_query"
      - "mysqli_query"
      - "$_GET in query"
      - "$_POST in query"

  xss:
    score: 8
    description: "Cross-Site Scripting (XSS)"
    patterns:
      - "unescaped output to HTML"
      - "echo without htmlspecialchars"
      - "print without escaping"
      - "raw user data in templates"
      - "bypass content sanitization"
      - "script injection vulnerability"
      - "missing HTML encoding"
      - "raw PHP output"
      - "direct variable output"
      - "unescaped $_GET"
      - "unescaped $_POST"

  input:
    score: 8
    description: "Insufficient Input Validation"
    patterns:
      - "input validation missing"
      - "unvalidated user input"
      - "unsafe type casting"
      - "user-controlled parameter"
      - "direct use of request parameters"
      - "no input sanitization"
      - "raw form data processing"
      - "missing input boundary checks"
      - "untrusted data handling"
      - "$_REQUEST without validation"
      - "$_GET without validation"
      - "$_POST without validation"

  data:
    score: 8
    description: "Sensitive Data Exposure"
    patterns:
      - "sensitive data exposure"
      - "plaintext credentials"
      - "hardcoded secrets"
      - "API keys in code"
      - "unencrypted sensitive data"
      - "information disclosure"
      - "data leakage"
      - "credentials in config files"
      - "sensitive data caching"
      - "debug information disclosure"
      - "phpinfo()"
      - "error_reporting(E_ALL)"

  session:
    score: 8
    description: "Session Management Issues"
    patterns:
      - "session fixation"
      - "insecure session handling"
      - "session hijacking risk"
      - "missing session timeout"
      - "weak session ID generation"
      - "session token exposure"
      - "cookie security missing"
      - "insufficient session expiration"
      - "session_start"
      - "$_SESSION"
      - "session_regenerate_id"

  config:
    score: 7
    description: "Security Misconfiguration"
    patterns:
      - "security misconfiguration"
      - "debug mode enabled"
      - "insecure permissions"
      - "missing security headers"
      - "verbose error messages"
      - "directory listing enabled"
      - "development settings in production"
      - "display_errors = On"
      - "allow_url_include = On"
      - "expose_php = On"

  logging:
    score: 7
    description: "Sensitive Data Logging"
    patterns:
      - "sensitive data in logs"
      - "password logging"
      - "PII in logs"
      - "token logging"
      - "unsafe error logging"
      - "debug logging in production"
      - "authentication data in logs"
      - "error_log"
      - "trigger_error"
      - "php://stderr"

  crypto:
    score: 8
    description: "Insecure Cryptographic Usage"
    patterns:
      - "weak encryption"
      - "insecure random number generation"
      - "weak hash algorithm"
      - "MD5 usage"
      - "SHA1 usage"
      - "static initialization vector"
      - "hardcoded encryption key"
      - "rand()"
      - "mt_rand()"
      - "mcrypt_encrypt"

  rce:
    score: 9
    description: "Remote Code Execution"
    patterns:
      - "eval with user input"
      - "exec function with variables"
      - "system call with parameters"
      - "shell_exec"
      - "passthru"
      - "proc_open"
      - "popen"
      - "include $_GET"
      - "require $_POST"
      - "create_function"

  ssrf:
    score: 7
    description: "Server-Side Request Forgery"
    patterns:
      - "URL fetching from user input"
      - "request module with variable URL"
      - "http client with dynamic endpoint"
      - "webhook implementation"
      - "dynamic API requests"
      - "file_get_contents"
      - "curl_exec"
      - "fopen"
      - "fsockopen"
      - "include/require remote URL"

  xxe:
    score: 7
    description: "XML External Entity Injection"
    patterns:
      - "XML parser without entity restrictions"
      - "XML processing without disabling DTD"
      - "unsafe DOM parser"
      - "XML libraries with dangerous defaults"
      - "simplexml_load_string"
      - "simplexml_load_file"
      - "DOMDocument"
      - "xml_parse"
      - "XMLReader"
      - "loadXML"

  pathtra:
    score: 8
    description: "Path Traversal"
    patterns:
      - "file operations with user input"
      - "path concatenation without validation"
      - "directory traversal vulnerability"
      - "reading files with variable paths"
      - "filepath not normalized"
      - "unsafe file access"
      - "include/require user input"
      - "fopen user input"
      - "file_get_contents user path"
      - "readfile user input"

  idor:
    score: 7
    description: "Insecure Direct Object Reference"
    patterns:
      - "user ID in URL parameters"
      - "missing access control checks"
      - "direct object reference in request"
      - "lack of authorization validation"
      - "resource ID manipulation vulnerability"
      - "authorization bypass risk"
      - "direct reference to database records"
      - "object level authorization missing"
      - "unsafe parameter handling"
      - "insufficient permission checking"

  secrets:
    score: 8
    description: "Hardcoded Secrets"
    patterns:
      - "hardcoded API key"
      - "password in source code"
      - "hardcoded credentials"
      - "embedded secret"
      - "private key in code"
      - "OAuth token in variables"
      - "secret key declaration"
      - "cleartext password"
      - "connection string with credentials"
      - "database password in code"

  auth:
    score: 8
    description: "Authentication Issues"
    patterns:
      - "weak password requirements"
      - "missing multi-factor authentication"
      - "insufficient credential handling"
      - "authentication bypass vulnerability"
      - "insecure password storage"
      - "broken authentication flow"
      - "credential reset weakness"
      - "session fixation vulnerability"
      - "insecure remember me function"
      - "inadequate brute force protection"

  csrf:
    score: 7
    description: "Cross-Site Request Forgery"
    patterns:
      - "missing CSRF token"
      - "state-changing operation without protection"
      - "form submission without CSRF verification"
      - "cookie-only authentication"
      - "missing SameSite attribute"
      - "actions without user confirmation"
      - "lack of request origin validation"
      - "missing anti-forgery token"
      - "insecure cross-domain requests"
      - "automatic actions without validation" 